### ISSUE TITLE
It still will not download after many tries

### ISSUE THREAD

**Issue by cloudyybaka** [BuIlDaLiBlE/BetterHI3Launcher#56] opened 2022-07-13 06:03 UTC
![Screenshot (4)](https://user-images.githubusercontent.com/97254181/178661923-b3d7d03f-f4ae-4d0c-8cf7-0e0ff95b3be1.png)

**Comment by BuIlDaLiBlE** [comment] 2022-07-13 06:20
Please do not open more issues, I'll be closing this as a duplicate of #55.

**Closed by BuIlDaLiBlE** 2022-07-13 06:20 UTC
Labels: bug

**Comment by cloudyybaka** [comment] 2022-07-13 06:24
> Please do not open more issues, I'll be closing this as a duplicate of #55.

Ok sorry, I just really want this to work
