### ISSUE TITLE
BetterGenshinLauncher

### ISSUE THREAD

**Issue by KingSlender** [BuIlDaLiBlE/BetterHI3Launcher#38] opened 2021-12-28 14:15 UTC
my request is really simple and it'd actually help a lot of the people in my country since we also have this problem. we would like the same launcher but instead of for honkai it'd be for genshin impact because we always get a problem with the game files getting deleted/corrupted and the troubleshooting in the customer support genshin gives doesn't help

**Comment by BuIlDaLiBlE** [comment] 2021-12-28 15:56
Duplicate of #24. I won't say I will never make it, just that there is no interest at the time.

**Closed** 2021-12-28 15:57 UTC
Labels: duplicate, suggestion
