### ISSUE TITLE
HELP: recurring installation error

### ISSUE THREAD

**Issue by NassyBunny** [BuIlDaLiBlE/BetterHI3Launcher#53] opened 2022-07-01 03:27 UTC
**Describe the bug**
I have been trying to install the game through the launcher about 2 or 3 times, and every time the download goes on for longer than it should and goes past the 100% mark (it'll display as 113%, for example.) It keeps going like that till it eventually stops and notifies me of an error. 

**Log**
ERROR: Failed to download the game:
System.Exception: Unhandled exception has been thrown on SessionID: 7128
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: from
   at System.Net.Http.Headers.RangeItemHeaderValue..ctor(Nullable`1 from, Nullable`1 to)
   at System.Net.Http.Headers.RangeHeaderValue..ctor(Nullable`1 from, Nullable`1 to)
   at Hi3Helper.Http.Http.<GetSessionMultisession>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hi3Helper.Http.Http.<>c__DisplayClass31_0.<<StartRetryableTask>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Hi3Helper.Http.Http.<StartRetryableTask>d__31.MoveNext() ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: from
   at System.Net.Http.Headers.RangeItemHeaderValue..ctor(Nullable`1 from, Nullable`1 to)
   at System.Net.Http.Headers.RangeHeaderValue..ctor(Nullable`1 from, Nullable`1 to)
   at Hi3Helper.Http.Http.<GetSessionMultisession>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hi3Helper.Http.Http.<>c__DisplayClass31_0.<<StartRetryableTask>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Hi3Helper.Http.Http.<StartRetryableTask>d__31.MoveNext()
   --- End of inner exception stack trace ---
   at Hi3Helper.Http.Http.<StartRetryableTask>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hi3Helper.Http.Http.<DownloadMultisession>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BetterHI3Launcher.MainWindow.<DownloadGameFile>d__68.MoveNext()

**Additional context**
I'm on the Global server and the HoYoverse mirror.

**Comment by BuIlDaLiBlE** [comment] 2022-07-01 06:18
Thanks for the report! The issue is now being investigated.

**Comment by NassyBunny** [comment] 2022-07-01 10:01
also tried the other mirror, this is the log I got.

ERROR: Failed to download the game:
System.Net.Http.HttpRequestException: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hi3Helper.Http.Http.<GetContentLength>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Hi3Helper.Http.Http.<TryGetContentLength>d__30.MoveNext() ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hi3Helper.Http.Http.<GetContentLength>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Hi3Helper.Http.Http.<TryGetContentLength>d__30.MoveNext()
   --- End of inner exception stack trace ---
   at Hi3Helper.Http.Http.<TryGetContentLength>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hi3Helper.Http.Http.<GetSessionAttributeCollection>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Hi3Helper.Http.Http.<DownloadMultisession>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BetterHI3Launcher.MainWindow.<DownloadGameFile>d__68.MoveNext()

**Comment by neon-nyan** [comment] 2022-07-03 17:34
Hi **@NassyBunny**, thank you for reporting this issue.
This is an issue on one of the submodule we use to download the file.

This issue has been addressed on [**this main submodule Pull-Request**](https://github.com/neon-nyan/Hi3HelperCore.Http/pull/1).

**@BuIlDaLiBlE** Do I have to make a PR on this repo? because what we need to do is just update the submodule.

**Comment by BuIlDaLiBlE** [comment] 2022-07-07 13:19
Addressed in [v1.3.20220707.0](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/releases/tag/1.3.20220707.0). 
**[neon-nyan](https://github.com/neon-nyan)**, much obliged!

**Closed by BuIlDaLiBlE** 2022-07-07 13:19 UTC
Labels: bug
