### ISSUE TITLE
help

### ISSUE THREAD

**Issue by cloudyybaka** [BuIlDaLiBlE/BetterHI3Launcher#55] opened 2022-07-12 06:33 UTC
![Screenshot (4)](https://user-images.githubusercontent.com/97254181/178424050-3f4c41ce-3178-467b-be4c-5122ee51e763.png)

**Comment by BuIlDaLiBlE** [comment] 2022-07-12 06:41
Can you elaborate about this? How many times you tried to download?

**Comment by cloudyybaka** [comment] 2022-07-12 06:55
> Can you elaborate about this? How many times you tried to download?

I have only tried once and that is when I got the error, I am now trying a second time, hopefully, it works.

**Comment by BuIlDaLiBlE** [comment] 2022-07-12 11:46
> I have only tried once and that is when I got the error, I am now trying a second time, hopefully, it works.

Is it ok now?

**Comment by cloudyybaka** [comment] 2022-07-12 17:37
> > I have only tried once and that is when I got the error, I am now trying a second time, hopefully, it works.
> 
> Is it ok now?

Nope, I left it to download overnight and I came back and it is still on the lan
![Screenshot (5)](https://user-images.githubusercontent.com/97254181/178556896-95224b8c-1767-4001-a52a-b4d93c62d075.png)
ch screen

**Comment by cloudyybaka** [comment] 2022-07-12 17:43
> > > I have only tried once and that is when I got the error, I am now trying a second time, hopefully, it works.
> > 
> > 
> > Is it ok now?
> 
> Nope, I left it to download overnight and I came back and it is still on the launch screen
> 
> ![Screenshot (5)](https://user-images.githubusercontent.com/97254181/178556896-95224b8c-1767-4001-a52a-b4d93c62d075.png)

![Screenshot (6)](https://user-images.githubusercontent.com/97254181/178558165-4131dc7b-c2f9-4062-87bc-da6fdb05db36.png)

**Comment by cloudyybaka** [comment] 2022-07-12 18:28
I am gonna try to download it again

**Comment by cloudyybaka** [comment] 2022-07-13 06:05
I have tried many times but it still says the same thing, what do you think I can do to fix it?

**Comment by BuIlDaLiBlE** [comment] 2022-07-13 06:51
Thanks for confirming. I could not reproduce the issue, can you try downloading to a different drive?

**Comment by BuIlDaLiBlE** [comment] 2022-07-13 07:07
Wait, I could reproduce it just now. Hang on while I investigate this...

**Comment by BuIlDaLiBlE** [comment] 2022-07-13 07:14
Can you please send a screenshot from `This PC` where all the available drives are shown?

**Comment by cloudyybaka** [comment] 2022-07-13 20:40
> Also, can you try to download the game again with this test build and report the error it will show? https://bpnet.work/files/bbh3l/TEST/BetterHI3Launcher.exe

BetterHI3Launcher v1.3.20220713.0 [TEST]
Working directory: C:\Users\Lueanne Estrada\Desktop\MICAH MOTTLEY\
OS version: Windows 10 Pro (Version 21H2, Build 19044.1826)
OS language: en-US
Launcher language: en (autodetect)
WARNING: Bp Network connection error, attempt №2...
Using server: Global
Using mirror: HoYoverse
Checking for game update...
Ready to install the game
Installation directory selected: C:\Users\Lueanne Estrada\Desktop\MICAH MOTTLEY\honkai test\Honkai Impact 3rd
Starting to download game archive: BH3_v5.8.0_3746462df53b.7z (https://d2wztyirwsuyyo.cloudfront.net/ptpublic/bh3_global/20220627152836_ZkkbE9mzDSszbFJz/BH3_v5.8.0_3746462df53b.7z)
CRITICAL ERROR: Unhandled exception occurred. Stack trace:
System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.__Error.FileNotOpen()
   at System.IO.FileStream.get_Length()
   at Hi3Helper.Http.Http.<>c.<WatchMultisessionEventProgress>b__20_1(SessionAttribute x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.Sum(IEnumerable`1 source)
   at Hi3Helper.Http.Http.<WatchMultisessionEventProgress>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by cloudyybaka** [comment] 2022-07-13 20:41
> Can you please send a screenshot from `This PC` where all the available drives are shown?
![Screenshot (7)](https://user-images.githubusercontent.com/97254181/178830484-a1c3a045-2e1c-45e1-ad7a-c89e011c66af.png)

**Comment by BuIlDaLiBlE** [comment] 2022-07-14 08:07
Thanks for the feedback, this will be investigated.

**Comment by BuIlDaLiBlE** [comment] 2023-01-11 20:14
Should be resolved as of [v1.4.20230111.0](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/releases/tag/1.4.20230111.0). Feel free to open another issue if you encounter any more errors.

**Closed by BuIlDaLiBlE** 2023-01-11 20:14 UTC
Labels: bug
