### ISSUE TITLE
Cannot connect to Hoyoverse servers?

### ISSUE THREAD

**Issue by Omegaxis8009** [BuIlDaLiBlE/BetterHI3Launcher#64] opened 2023-02-13 23:36 UTC
**Describe the bug**
There seems to be an irregular bug with the launcher trying to connect to servers, sometimes it works properly, sometimes it does not.

**To Reproduce**
Open launcher
Get error message

**Expected behavior**
For the launcher to start

**Log**
[BetterHI3Launcher-latest.log](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/files/10727184/BetterHI3Launcher-latest.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/17508506/218598112-735e3d42-a0e2-4583-90c1-8f62bec29e7c.png)

**Additional context**
Game launches normally through the BH3.exe, it is only the launcher that's seemingly having issues. And there appears to be no issues with my internet since Discord and Chrome are working fine.

**Comment by BuIlDaLiBlE** [comment] 2023-02-15 21:05
This is an old bug, the cause of which is hard to determine due to it seemingly happening at random.
The log is not of much use as it seems like the error occurs somewhere outside the main thread, which is most likely UI thread.
Ultimately, I think it may a bug with WPF or the way the launcher is using the UI elements, but I haven't been able to reproduce this bug to fix it.

**Comment by BuIlDaLiBlE** [comment] 2023-12-08 08:20
Finally tracked down the issue, in the latest version the crash is actually an unhandled exception but will be fixed in the next release.

**Comment by BuIlDaLiBlE** [comment] 2023-12-19 19:19
Addressed in [v1.5.20231219.0](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/releases/tag/1.5.20231219.0).

**Closed by BuIlDaLiBlE** 2023-12-19 19:19 UTC
Labels: bug
